version: "3"
services:
  # db containers
  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./db_data:/var/lib/cassandra
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u cassandra",
          "-p cassandra",
          "-e describe keyspaces",
        ]
      interval: 15s
      timeout: 10s
      retries: 10

  # db schema initializer
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:3.11.2
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./config/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  # application service container
  app:
    container_name: curfetch
    build: ./
    ports:
      - "8080:8080"
    environment:
      CASS_HOST: cassandra
      CASS_KEYSPACE: curfetch
      CASS_USERNAME: cassandra
      CASS_PASSWORD: cassandra
    command: curfetch serve
    depends_on:
      - cassandra-load-keyspace
